### ISSUE TITLE
the best way for creating a flat shape of shapes  for  exporting?

### ISSUE THREAD

**Issue by zoghal** [saniainf/CorelDraw#1]
hi dear
I'm looking for a good way to create a flat shape to export svg.
i try to use Shape.Seld but i failure
Can you guide me?
thanks
![screenshot 2015-09-24 12 43 11](https://cloud.githubusercontent.com/assets/174688/11517960/ada90c84-98a2-11e5-967d-ee4113d8f477.png)

**Comment by saniainf** [comment]
hi
sry, i don't understand what you need to do
i create corel script on vba 
Class Shape not contain method Seld

**Comment by saniainf** [comment]
my english translate by google ))

**Comment by saniainf** [comment]
Sub Macro1()
    Application.Optimization = True
    Dim s1 As Shape
    Dim sr As ShapeRange
    Set sr = ActiveSelectionRange
    Set s1 = sr.FirstShape.Duplicate
    For i = 2 To sr.Count
        Dim s2 As Shape
        Set s2 = s1.Weld(sr.Item(i), False, False)
        Set s1 = s2
    Next i
    sr.FirstShape.Delete
    Application.Optimization = False
    ActiveWindow.Refresh
    Application.Refresh
End Sub

**Comment by saniainf** [comment]
Sub Macro1()
    Application.Optimization = True
    Dim s1 As Shape
    Dim sr As ShapeRange
    Set sr = ActiveSelectionRange
    Set s1 = sr.FirstShape.Duplicate
    For i = 2 To sr.Count
        Dim s2 As Shape
        Set s2 = s1.Weld(sr.Item(i), False, False)
        Set s1 = s2
    Next i
    sr.FirstShape.Delete
    Application.Optimization = False
    ActiveWindow.Refresh
    Application.Refresh
End Sub

**Comment by zoghal** [comment]
thanks :+1: 

i use this method

```
Sub doWeildAllShape()
   Dim s As Shape, con As Integer
    ActiveDocument.BeginCommandGroup "kkk"
    On Error GoTo ErrHandler
    ActiveDocument.Unit = cdrPixel
    ActiveLayer.Shapes.All.CreateSelection
    Set sh = ActiveDocument.SelectionRange
    con = sh.Count
    If con < 2 Then
        Exit Sub
    End If
    For i = 1 To con - 1
        Set s = ActiveLayer.Shapes(1).Weld(ActiveLayer.Shapes(2), False, False)
        ActiveLayer.Shapes(1).Curve.Nodes.All.AutoReduce 1
    Next i

ExitSub:
        ActiveDocument.EndCommandGroup
    Exit Sub
ErrHandler:
    MsgBox "Error occured: " & Err.Description
    ActiveDocument.Undo
    Resume ExitSub
End Sub
```
